name: Generate JSON if needed

on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run script
      run: php wc-barcelona-xml-to-js.php

    # Commit and push all changed files.
    - name: Commit and push
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'schedule'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
