name: Generate JSON if needed

on:
  schedule:
    - cron: '0/5 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run script
      run: php wc-barcelona-xml-to-js.php

    - name: Commit and push
      if: github.event_name == 'schedule'
      run: |
        git config --global user.name "$CI_COMMIT_NAME"
        git config --global user.email "$CI_COMMIT_EMAIL"
        git add wc.js
        git commit -m "$CI_COMMIT_MESSAGE"
        git push
