name: Generate JSON if needed

on:
  schedule:
    - cron: '0 8 * * 1,3,5'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run script
      run: php wc-barcelona-xml-to-js.php

    - name: Commit and push
      if: github.event_name == 'schedule'
      run: |
        if [ false ]; then
          echo "No changes to commit"
          exit 0
        fi
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add wc.js index.html
        git commit -m "${{ vars.CI_COMMIT_MESSAGE }}" 
        git push
